### ISSUE TITLE
1.15.2-4.10[crash on launch]

### ISSUE THREAD

**Issue by SDUBZ** [Szewek/Flux#12]
[Render thread/ERROR]: Exception caught during firing event: szewek.fl.util.FluxItemTier.<init>(IIFFILjava/lang/String;Lnet/minecraft/item/Item;)V
**Versions:**
- **Minecraft:** 1.15.2
- **Forge:** 31.1.18
- **Flux Library:** fl-3.1.0
- **Flux:** flux-4.10.0

**Logs:** {Link(s) to GitHub Gist (or Pastebin) with full `latest.log` and/or crash report}
[latest.log](https://github.com/Szewek/Flux/files/4323294/latest.log)

**Steps to Reproduce:**
 1.load up with above version mentioned
 2. get a crashing result

**Description of issue:**
something not getting registered in renders correctly i think
java.lang.NoSuchMethodError: szewek.fl.util.FluxItemTier.<init>(IIFFILjava/lang/String;Lnet/minecraft/item/Item;)V

**Comment by SDUBZ** [comment]
wait might be other mod
Let me know if you can confirm

**Comment by kreezxil** [comment]
confirmed

Issue:  flux 4.10.0 crashes dedicated server Forge 1.15.2 build 31.1.19

Notes:
     No Such Method Error

crash report: 
http://paste.ubuntu.com/p/RcN8Zg4ccW/

fml server latest: 
http://paste.ubuntu.com/p/F8N3Tq8fsK/

**Comment by kreezxil** [comment]
## note
4.9.1 works fine with fl 3.1.0

**Comment by Szewek** [comment]
The problem from #11 was fixed in FL and changes were applied for Flux too quickly. Flux has still requirement for 3.1.0 even if fix didn't exist in that version.

I released new versions of both Flux and FL to fix the requirements.
Flux 4.10.1: https://www.curseforge.com/minecraft/mc-mods/flux/files/2899447
FL 3.1.1: https://www.curseforge.com/minecraft/mc-mods/fl/files/2899443
